modLoader="javafml"
loaderVersion="[37,)" 
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="elementalcraft"
version="${file.jarVersion}"
displayName="ElementalCraft"
description='''ElementalCraft is a magic mod based around the 4 elements: fire, water, earth and air.'''

[[dependencies.elementalcraft]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="dpanvil"
    mandatory=true
    versionRange="[1.17.1-2.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="jei"
    mandatory=false
    versionRange="[FORGE-1.16.5-7.7.0.106,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.16.2-47,)"
    ordering="AFTER"
    side="BOTH"
    